### ISSUE TITLE
HTTP cache?

### ISSUE THREAD

**Issue by Eglin** [MaciekBaron/PSPLUSTilesTheme#2]
What's the /kamaji/api/pcnow/00_09_000/user/stores stuff?  A local HTTP cache?  Is the script useful without it?  Your installation instructions don't mention generating this cache.  Am I missing something obvious?  

The inventor (or whatever title is appropriate) is now linking to your script with the suggestion to use it, but as far as I can tell nobody following your instructions would be able to.  Was there a previous revision that pulled directly from Sony's website that "everyone else" is using?

Thanks

**Comment by MaciekBaron** [comment]
No, that's a remote location.

Could you actually explain if you're having an issue, and if so, what is the issue you're encountering? Is that a 404?

**Comment by Eglin** [comment]
Hey, thanks.  I just got "Search (loading)" or whatever in the searchbar indefinitely.  I let it run for 15 minutes or more, but it never ended and search never became available.  The alternative script finishes loading pretty quickly on the same installation.  I believe I've followed your instructions to the letter and all the other changes (layout, floating headers, etc) all seem to work (nice job, that).  But the critically important search feature is not working for me.

**Comment by MaciekBaron** [comment]
Thanks, I'll look into it, it's likely that the URL has changed.

**Comment by MaciekBaron** [comment]
I think your API url might be different - I haven't had a chance to test this with a different account or locale, but if you open developer tools and look at XHR requests being made, the second one (to 'session') made will use the correct API call:

![image](https://user-images.githubusercontent.com/1668712/183754191-ab8f7821-892f-4d35-93d3-46417d491952.png)

Could you have a look what it is in your app? You can open the dev tools with CTRL + SHIFT + i, then go to Network and click on the XHR tab.

(You might need to refresh the page so that it records the traffic again)

**Comment by MaciekBaron** [comment]
I figured out a hacky way to retrieve that URL automatically. I've updated the code - let me know if it works for you now.

**Comment by Eglin** [comment]
Thanks very much for taking a look.  I stepped through your code in the debugger and can see that the data array is being properly populated with the name/id/platform fields but then throwing an unhandled exception when trying to index into an apparently empty `document.querySelectorAll(``[data-game="${id}"]``)` structure.  

Is it perhaps related to a 404 not found I get (even with the bone stock script shipping with the PS+ app) on startup (GET https://psnow.playstation.com/store/api/pcnow/00_09_000/container/US/en/XXXXXetc 404 - redacted because IDK if it's the URL is personal to me or not)?  That error maps to something deep within vendor.js and IDK what fetches the page, but it happens between the fetch for "stores" and "psNowHome?country=blahblah."  Is it possible that the data you're relying on is only present for your region?

**Comment by MaciekBaron** [comment]
Thanks for providing the extra info, this should help to figure out how to make it work for all regions. How many of those 404 errors do you get?

**Comment by Eglin** [comment]
OK, I think I've finally managed to wrap my head around this.  _Sorry if I sent you on a wild goose chase_, but I haven't studied HTML since version 3 (easier than making a Reddit post or using BBCode) and have never been a JavaScript person.  My idol used to say that if someone sent him two lines of buggy code, he _would_ find the issue.  If they sent him a page of code, he _might_ find the issue.  And if they sent him reams, he wouldn't try.  LOL.  Fortunately, this one wasn't too bad even for my untrained eyes thanks to your troubleshooting help.

Some of the games evidently do not have a playable_platform tag.  Specifically, it's Strongbad 1-3... which coincidentally are marked in the game list with an asterisk keyed against "*Availability of games vary by country/region."  Could explain why it isn't affecting you.  The following workaround does the trick, though a better solution would probably sanity check againts the parent structure's platform tag instead of assuming that the malformed entry must be a PS3 game.

tile.setAttribute('data-game-platform', playable_platform ? playable_platform.join('/') : 'PS3™');

Cheers!

**Comment by Eglin** [comment]
OK, sorry for sending you on a wild goose chase.  HTML and Javascript are not in my wheelhouse and I don't learn as quickly as I used to.

Some of the titles (Strongbad 1,2,3) are missing the playable_platform element.  These probably aren't available in your region.  Temporary workaround of

tile.setAttribute('data-game-platform', playable_platform ? playable_platform.join('/') : 'PS3™');

suffices, though a better solution would probably not assume the malformed records were all for PS3 games.


Thanks for your great script.  I'm glad to have it working for me now.

**Comment by Eglin** [comment]
OK, sorry for sending you on a wild goose chase.  HTML and Javascript are not in my wheelhouse and I don't learn as quickly as I used to.  I should've just reported the issues and let you do the troubleshooting!  Sorry.

Some of the titles (Strongbad 1,2,3) are missing the playable_platform element.  These probably aren't available in your region.  Temporary workaround of

tile.setAttribute('data-game-platform', playable_platform ? playable_platform.join('/') : 'PS3™');

suffices, though a better solution would probably not assume the malformed records were all for PS3 games.


Thanks for your great script.  I'm glad to have it working for me now.

**Comment by MaciekBaron** [comment]
Nice one, thanks! I'll update the code to make sure it doesn't crash if that doesn't exist.
