### ISSUE TITLE
Titles are doubled

### ISSUE THREAD

**Issue by ihorbond** [MaciekBaron/PSPLUSTilesTheme#3]
Hey thanks for this, search bar was MUCH needed! Just wanted to report that I'm seeing all titles doubled now, I'm in the US.
![image](https://user-images.githubusercontent.com/15573624/187563370-6023cc13-9903-41ef-8015-e84bb9df59fb.png)

**Comment by MaciekBaron** [comment]
Hi @ihorbond, thanks for reporting this. Are they doubled up in every category?

The tiles are normally doubled up (that's how they created the looped carousels), but I wrote a function to remove that. It's possible that this group is loaded later and does not get filtered.

**Comment by ihorbond** [comment]
> Hi @ihorbond, thanks for reporting this. Are they doubled up in every category?
> 
> The tiles are normally doubled up (that's how they created the looped carousels), but I wrote a function to remove that. It's possible that this group is loaded later and does not get filtered.

Actually, just checked again and it's all good now, it fixed itself after a restart I guess.
